Update Jenkinsfile

diff --git a/devops/Jenkinsfile b/devops/Jenkinsfile
--- a/devops/Jenkinsfile
+++ b/devops/Jenkinsfile
@@ -14,6 +14,7 @@ pipeline {
      //CI_IMAGE = "java-ci-tools:${env.BUILD_NUMBER}"
      MVN_IMAGE =  'maven:3.9.6-eclipse-temurin-17'
      IMAGE_REPO_LOCAL = 'devops_training-java-app'
+     APP_URL = 'http://localhost:8084/hello'
   }
 
   stages {
@@ -90,6 +91,7 @@ pipeline {
         steps {
           script {
             // Definir entorno de despliegue
+            echo "CD habilitado: RUN_CD=${params.RUN_CD}, branch=${env.BRANCH_NAME}"  
             env.DEPLOY_ENV = (env.BRANCH_NAME == 'main') ? 'PRO' : 'DEV'
             echo "Deploy env: ${env.DEPLOY_ENV}"
       
@@ -107,7 +109,10 @@ pipeline {
             echo "Cleanup done"
           }
           success { echo 'SUCCESS' }
-          failure { echo 'FAILURE' }
+          failure { 
+             echo 'FAILURE' 
+             sh 'docker compose logs || true'
+          }
         }
       }
   }
